package org.bleachhack.util.doom.boom;

import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import org.bleachhack.util.doom.wad.CacheableDoomObject;

/**
 *  LineSeg, generated by splitting LineDefs
 * using partition lines selected by BSP builder.
 * MAES: this is the ON-DISK structure. The corresponding memory structure, 
 * segs_t, has fixed_t members. 
 */

public class mapseg_v4_t implements CacheableDoomObject{
    
    public mapseg_v4_t(){
        
    }

  	public int v1;
  	public int v2;
  	public char angle;
  	public char linedef;
  	public char side;
  	public char offset;
   
   public static int sizeOf(){
       return 16;
   }
   
   @Override
   public void unpack(ByteBuffer buf)
           throws IOException {
       buf.order(ByteOrder.LITTLE_ENDIAN);
       this.v1 = buf.getInt();
       this.v2 = buf.getInt();
       this.angle=buf.getChar();       
       this.linedef=buf.getChar();
       this.side=buf.getChar();
       this.offset=buf.getChar();
      
   }
   
 };
